### ISSUE TITLE
Update RabbitMQ benchmark with new Streams data structure

### ISSUE THREAD

**Issue by kishansairam9** [confluentinc/openmessaging-benchmark#19]
RabbitMQ recently introduced Streams ([blog post](https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-overview/)) which are closer to Kafka semantics and offers higher through put over queues. 

Current benchmark has limited throughput with RabbitMQ to 30 MB/s so that latency doesn't degrade. Benchmarks should be updated with streams to represent recent developments.

**Comment by aloknnikhil** [comment]
Absolutely. Can you submit a PR to update the RabbitMQ runs?

**Comment by kishansairam9** [comment]
I have started learning about RabbitMQ recently, so might not be the best to write a benchmark. If anyone else is interested to take this up, it would be great, or else I'll give it a shot.

**Comment by kishansairam9** [comment]
@aloknnikhil streams protocol doesn't support partitions yet. It's present in roadmap.
Same is the case with Consumer Set. Currently though it supports multiple consumers, they are independent and have their own offsets.

Should we wait till they are available?
