### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Hyk1** [confluentinc/openmessaging-benchmark#6]
In the bin directory, there is no benchmark. So how to test it? like
sudo bin/benchmark \
  --drivers driver-kafka/kafka.yaml \
  workloads/1-topic-16-partitions-1kb.yaml

**Comment by aloknnikhil** [comment]
Thanks for pointing that out. It was removed in error. It's now restored - https://github.com/confluentinc/openmessaging-benchmark/commit/6d9e0f0b7320b062399bc70331377f0b037081bd
