### ISSUE TITLE
Invalid tasks in the kafka ansible playbook and invalid region specified

### ISSUE THREAD

**Issue by TKTheTechie** [confluentinc/openmessaging-benchmark#8]
The first two tasks in the ansible playbook https://github.com/confluentinc/openmessaging-benchmark/blob/master/driver-kafka/deploy/deploy.yaml appear to be invalid

Namely the `- name: Collect profiles` and the ` - name: Heap allocation profile` are both invalid since they seem to refer to files in `/tmp`. Not exactly sure where these files come from.

In addition, the region specified on line 70 in https://github.com/confluentinc/openmessaging-benchmark/blob/master/driver-kafka/deploy/provision-kafka-aws.tf needs to be changed to us-west-2a as 2b is not supported per the CLI output.

**Comment by aloknnikhil** [comment]
The profile tasks are to be run post-deployment. We don't have any use for that for the purpose of running the benchmark. You could skip those tasks by excluding those tags
```
# Note: We are using the terraform inventory here to populate the inventory list from Terraform
TF_STATE=. ansible-playbook -vv deploy.yaml --inventory `which terraform-inventory` --user 'ec2-user' --skip-tags 'profile'
```

> In addition, the region specified on line 70 in https://github.com/confluentinc/openmessaging-benchmark/blob/master/driver-kafka/deploy/provision-kafka-aws.tf needs to be changed to us-west-2a as 2b is not supported per the CLI output.

We have not had any issues in provisioning the setup in us-west-2b. What is the error from the CLI output specifically?

**Comment by TKTheTechie** [comment]
Thanks for the prompt feedback. Yes you are right - us-west-2b does not result an error for me anymore. May have been an account specific issue wrt limits.
